# Generated by Django 3.2.9 on 2021-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20211209_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='key',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
